# Utiliser une image Node.js officielle
FROM node:16

# Créer le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier le reste du code
COPY . .

# Exposer le port que Vite utilise par défaut (5173)
EXPOSE 5173

# Lancer l'application React en mode développement
CMD ["yarn", "dev", "--host"]