# Stage 1: Build the frontend
FROM node:18-alpine3.19 AS build
WORKDIR /app

# Install dependencies using npm
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the source code and build it
COPY . .
RUN npm run build  # This creates the dist folder
