version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 for the reverse proxy
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf  # Mount the custom Nginx config
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src/app  # Recharger les fichiers locaux
      - /usr/src/app/node_modules
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app  # Recharger les fichiers locaux
      - /usr/src/app/node_modules
    environment:
      - VITE_API_URL=http://localhost/api  # Access backend via service name
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: exampleuserpassword
      POSTGRES_DB: djiboutiport
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"  # Expose pgAdmin on port 8081
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: