version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod  # Use a production Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod  # Use the updated production Dockerfile
      args:
        VITE_API_URL: "http://146.59.239.14/api"  # Pass the build argument
    environment:
      - VITE_API_URL=http://146.59.239.14/api  # Optional, for runtime use
    networks:
      - app-network
    volumes:
      - ./frontend/dist:/app/dist  # Mount the host's dist directory to store built frontend
    command: ["npm", "run", "build"]  # Run the build command

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 for the reverse proxy and frontend
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf  # Use your custom Nginx config
      - ./frontend/dist:/usr/share/nginx/html  # Mount the built dist directory from host
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
