version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 for the reverse proxy
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf  # Use your custom Nginx config
      - frontend-build:/usr/share/nginx/html  # Mount the shared named volume to serve frontend
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod  # Use a production Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod  # Use a production Dockerfile
      args:
        VITE_API_URL: "http://nginx/api"  # Pass the build argument
    environment:
      - VITE_API_URL=http://nginx/api  # Access backend via reverse proxy (optional, for runtime use)
    networks:
      - app-network
    volumes:
      - frontend-build:/app/dist  # Mount the shared named volume to store built frontend

networks:
  app-network:
    driver: bridge

volumes:
  frontend-build:
