version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod  # Use a production Dockerfile
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET=your_jwt_secret
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod  # Use the updated multi-stage Dockerfile
      args:
        VITE_API_URL: "http://nginx/api"  # Pass the build argument
    ports:
      - "80:80"  # Expose port 80 for the reverse proxy and frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
