# Utiliser une image Node.js officielle
FROM node:16

# Créer le répertoire de travail dans le conteneur
WORKDIR /usr/src/app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install

# Copier tout le code dans le conteneur
COPY . .

# Copy the wait-for-it.sh script into the image and make it executable
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Installer nodemon pour le rechargement automatique pendant le développement
RUN npm install -g nodemon

# Exposer le port que l'application utilise
EXPOSE 5001

# Commande pour démarrer l'application en mode développement
CMD ["/wait-for-it.sh", "db:5432", "--", "nodemon", "server.js"]